import { z } from "zod";

/**
 * How much a piece of information can be trusted.
 * - verified: taken directly from the job posting or the user's own resume.
 * - source_backed: stated by an external source we retrieved (official or reputable).
 * - candidate_reported: reported by candidates (interview reports, forums).
 * - inferred: derived by Elevate from verified data with a deterministic or AI step.
 * - predicted: generated by Elevate; never presented as fact.
 */
export const EvidenceType = z.enum([
  "verified",
  "source_backed",
  "candidate_reported",
  "inferred",
  "predicted",
]);
export type EvidenceType = z.infer<typeof EvidenceType>;

export const EvidenceOrigin = z.enum(["job_posting", "resume", "research", "elevate"]);
export type EvidenceOrigin = z.infer<typeof EvidenceOrigin>;

export const EvidenceRef = z.object({
  type: EvidenceType,
  origin: EvidenceOrigin,
  /** Exact text that supports the claim, when one exists. Verified against the origin text. */
  quote: z.string().max(600).nullable(),
  /** IDs of research_sources rows supporting the claim. */
  sourceIds: z.array(z.string()).default([]),
});
export type EvidenceRef = z.infer<typeof EvidenceRef>;
